//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtlReporteria.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings_etl : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_etl defaultInstance = ((Settings_etl)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_etl())));
        
        public static Settings_etl Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost\\SOFTLAND_TEST")]
        public string ServidorSqlDestino {
            get {
                return ((string)(this["ServidorSqlDestino"]));
            }
            set {
                this["ServidorSqlDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.101\\GPICB")]
        public string ServidorSqlTarget {
            get {
                return ((string)(this["ServidorSqlTarget"]));
            }
            set {
                this["ServidorSqlTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string UsuarioSqlDestino {
            get {
                return ((string)(this["UsuarioSqlDestino"]));
            }
            set {
                this["UsuarioSqlDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Colocolo25")]
        public string ContrasenaSqlDestino {
            get {
                return ((string)(this["ContrasenaSqlDestino"]));
            }
            set {
                this["ContrasenaSqlDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportSqlServerInformation")]
        public string DatabaseDestino {
            get {
                return ((string)(this["DatabaseDestino"]));
            }
            set {
                this["DatabaseDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("falmeida_UAT")]
        public string UsuarioSqlTarget {
            get {
                return ((string)(this["UsuarioSqlTarget"]));
            }
            set {
                this["UsuarioSqlTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sys.aqswfa")]
        public string ContrasenaSqlTarget {
            get {
                return ((string)(this["ContrasenaSqlTarget"]));
            }
            set {
                this["ContrasenaSqlTarget"] = value;
            }
        }
    }
}
