USE msdb;
GO
DECLARE @ayer INT = CONVERT(INT, CONVERT(VARCHAR(8), DATEADD(DAY, -1, GETDATE()), 112));
EXEC sp_help_jobhistory 
    @start_run_date = @ayer;
GO

USE VNT; 
--EXEC sp_spaceused;

ALTER DATABASE VNT SET RECOVERY SIMPLE; 
DBCC SHRINKFILE (VNT, 0, TRUNCATEONLY);

ALTER DATABASE VNT SET RECOVERY FULL ; 
